#!/usr/bin/env Rscript
# Regenerate R/bundled_sha256.R from bridge/dist/SHA256SUMS.
#
# Run after every bridge release; commit the diff alongside the SDK
# release that targets it.
#
# Usage (from publishers/r/):
#   Rscript tools/update_sha256.R 0.1.0
#
# Expects bridge/dist/SHA256SUMS to exist (produced by `make release`
# in bridge/).

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L) {
  stop("Usage: Rscript tools/update_sha256.R <bridge-version>", call. = FALSE)
}
version <- args[[1]]

sums_file <- file.path("..", "..", "bridge", "dist", "SHA256SUMS")
if (!file.exists(sums_file)) {
  stop("Cannot find ", normalizePath(sums_file, mustWork = FALSE),
       "\nRun `make release` from bridge/ first.", call. = FALSE)
}

lines <- readLines(sums_file)
sums <- list()
for (line in lines) {
  parts <- strsplit(trimws(line), "\\s+")[[1]]
  if (length(parts) != 2L) next
  hash <- parts[[1]]
  filename <- parts[[2]]
  # Filename: "fernsicht-bridge-<platform-arch>[.exe]"
  platform <- sub("^fernsicht-bridge-", "", filename)
  sums[[platform]] <- hash
}

required <- c("linux-amd64", "linux-arm64",
              "darwin-amd64", "darwin-arm64",
              "windows-amd64.exe")
missing <- setdiff(required, names(sums))
if (length(missing) > 0L) {
  stop("Missing SHA256 entries for: ", paste(missing, collapse = ", "),
       call. = FALSE)
}

# Write R/bundled_sha256.R with stable formatting.
items <- vapply(required,
  function(p) sprintf('  "%s" = "%s"', p, sums[[p]]),
  character(1))

out_lines <- c(
  "# Auto-generated by tools/update_sha256.R; DO NOT EDIT by hand.",
  "# Bumped per bridge release.",
  "",
  sprintf('BRIDGE_VERSION <- "%s"', version),
  "",
  "BUNDLED_SHA256 <- list(",
  paste(items, collapse = ",\n"),
  ")",
  ""
)

dest <- file.path("R", "bundled_sha256.R")
writeLines(out_lines, dest)
cat("Wrote ", dest, " (bridge v", version, ")\n", sep = "")
