package main

import (
	"fmt"
	"os"
	"strings"
)

// completionCommand handles `fernsicht completion {bash|zsh|fish|powershell}`.
//
// Hand-rolled completion scripts (we don't depend on cobra). Each
// shell gets a static template — our subcommand surface is small
// enough that this stays maintainable.
//
// Install (per shell):
//
//   bash:        fernsicht completion bash > /etc/bash_completion.d/fernsicht
//                # or for one shell session: source <(fernsicht completion bash)
//   zsh:         fernsicht completion zsh > "${fpath[1]}/_fernsicht"
//   fish:        fernsicht completion fish > ~/.config/fish/completions/fernsicht.fish
//   powershell:  fernsicht completion powershell >> $PROFILE
func completionCommand(args []string) int {
	if len(args) < 1 {
		fmt.Fprintln(os.Stderr,
			"[fernsicht] error: missing shell name.")
		fmt.Fprintln(os.Stderr,
			"Usage: fernsicht completion {bash|zsh|fish|powershell}")
		return 2
	}
	shell := strings.ToLower(args[0])
	var script string
	switch shell {
	case "bash":
		script = bashCompletion
	case "zsh":
		script = zshCompletion
	case "fish":
		script = fishCompletion
	case "powershell", "pwsh":
		script = powershellCompletion
	default:
		fmt.Fprintf(os.Stderr,
			"[fernsicht] error: unsupported shell %q\n", shell)
		fmt.Fprintln(os.Stderr,
			"Supported: bash, zsh, fish, powershell")
		return 2
	}
	fmt.Print(script)
	return 0
}

// Subcommand list — kept here in one place so the completion scripts
// stay in sync with main's dispatch table. Keep alphabetized.
const subcommandList = "completion doctor help magic run update url version"

// runFlagsList — flags supported by `fernsicht run`. Used by bash/zsh
// to suggest flags after `fernsicht run`. Kept as a flat space-
// separated list because most users just hit Tab once and pick.
const runFlagsList = "" +
	"--no-pty --no-unbuffer --debug " +
	"--no-detect --no-magic --strict-magic " +
	"--server-url --join-secret --max-viewers --label " +
	"--share --quiet --qr --no-qr --no-fail-on-bridge " +
	"--unit --pattern --copy-url --strict --output --config --url-file --webhook"

const bashCompletion = `# fernsicht completion for bash. Install:
#   source <(fernsicht completion bash)         # this shell only
#   fernsicht completion bash > /etc/bash_completion.d/fernsicht  # system-wide
#
# Generated by ` + `fernsicht completion bash` + `. Re-run after upgrading
# fernsicht to pick up new subcommands / flags.

_fernsicht() {
    local cur prev cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # If we're completing the first non-script word, suggest subcommands.
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${subcommandList} --help --version" -- "$cur") )
        return 0
    fi

    # The first non-flag word after "fernsicht" is the subcommand.
    cmd="${COMP_WORDS[1]}"
    case "$cmd" in
        run)
            # After "run --", anything goes; before "--", we suggest flags.
            for w in "${COMP_WORDS[@]}"; do
                if [ "$w" = "--" ]; then return 0; fi
            done
            COMPREPLY=( $(compgen -W "${runFlagsList} --" -- "$cur") )
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- "$cur") )
            ;;
        url)
            COMPREPLY=( $(compgen -W "--all --pid" -- "$cur") )
            ;;
        doctor)
            COMPREPLY=( $(compgen -W "--explain --server-url --no-color" -- "$cur") )
            ;;
        update)
            COMPREPLY=( $(compgen -W "--check" -- "$cur") )
            ;;
    esac
}
complete -F _fernsicht fernsicht
`

const zshCompletion = `#compdef fernsicht
# fernsicht completion for zsh. Install:
#   fernsicht completion zsh > "${fpath[1]}/_fernsicht"
# Then re-run ` + `compinit` + `.

_fernsicht() {
    local -a subcommands
    subcommands=(
        'run:Wrap a command; broadcast its progress to a viewer URL'
        'url:Print URL of running session(s)'
        'doctor:Diagnose installation / network'
        'magic:Show the magic-prefix protocol reference'
        'completion:Generate shell completion scripts'
        'update:Check for or install a newer version'
        'version:Print version + build info'
        'help:Show help'
    )
    if (( CURRENT == 2 )); then
        _describe 'subcommand' subcommands
        return
    fi

    local cmd=$words[2]
    case $cmd in
        run)
            local -a runflags
            runflags=(${(f)"${runFlagsList//[[:space:]]+/$'\n'}"})
            _arguments '*::flag:->run_flags'
            case $state in
                run_flags)
                    _values 'fernsicht run flag' \
                        '--no-pty[do not allocate a pty]' \
                        '--no-unbuffer[do not set PYTHONUNBUFFERED=1 etc]' \
                        '--debug[verbose internal logging]' \
                        '--no-detect[disable Tier-1 auto-detection]' \
                        '--no-magic[do not intercept magic-prefix lines]' \
                        '--strict-magic[exit 250 on invalid magic-prefix line]' \
                        '--server-url[signaling server URL]:url' \
                        '--join-secret[server auth]:secret' \
                        '--max-viewers[cap concurrent viewers]:n' \
                        '--label[task label shown to viewers]:label' \
                        '--share[print URL on stdout, suppress chrome]' \
                        '--quiet[suppress fernsicht own output]' \
                        '--qr[force QR code rendering]' \
                        '--no-qr[suppress QR code rendering]' \
                        '--no-fail-on-bridge[run wrapped command even if bridge open fails]' \
                        '--unit[progress unit shown to viewers]:unit' \
                        '--pattern[custom regex pattern]:regex' \
                        '--copy-url[copy URL to system clipboard]' \
                        '--strict[bridge failure mid-run -> exit 200]' \
                        '--output[output mode (text|json)]:mode:(text json)' \
                        '--config[explicit .fernsicht.toml path]:path:_files' \
                        '--url-file[override URL file path]:path:_files' \
                        '--webhook[POST JSON to URL on session end]:url'
                    ;;
            esac
            ;;
        completion)
            _values 'shell' bash zsh fish powershell
            ;;
        url)
            _values 'url flag' '--all[show all sessions]' '--pid[specific PID]:pid'
            ;;
        doctor)
            _values 'doctor flag' \
                '--explain[error code lookup]:code' \
                '--server-url[probe a different server]:url' \
                '--no-color[disable colored output]'
            ;;
        update)
            _values 'update flag' '--check[check only, do not install]'
            ;;
    esac
}
_fernsicht "$@"
`

const fishCompletion = `# fernsicht completion for fish. Install:
#   fernsicht completion fish > ~/.config/fish/completions/fernsicht.fish

# Subcommands.
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'run'        -d 'Wrap a command; broadcast progress'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'url'        -d 'Print URL of running session(s)'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'doctor'     -d 'Diagnose installation / network'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'magic'      -d 'Magic-prefix protocol reference'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completion'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'update'     -d 'Check for / install a newer version'
complete -c fernsicht -f -n '__fish_use_subcommand' -a 'version'    -d 'Print version + build info'

# completion shell list
complete -c fernsicht -f -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish powershell'

# url flags
complete -c fernsicht -f -n '__fish_seen_subcommand_from url' -l all -d 'Show every running session'
complete -c fernsicht -f -n '__fish_seen_subcommand_from url' -l pid -d 'Specific PID'

# doctor flags
complete -c fernsicht -f -n '__fish_seen_subcommand_from doctor' -l explain    -d 'Error code lookup'
complete -c fernsicht -f -n '__fish_seen_subcommand_from doctor' -l server-url -d 'Probe a different server'
complete -c fernsicht -f -n '__fish_seen_subcommand_from doctor' -l no-color   -d 'Disable colored output'

# update flags
complete -c fernsicht -f -n '__fish_seen_subcommand_from update' -l check -d 'Check only, do not install'

# run flags (commonly used; the full list is in fernsicht run --help)
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-pty
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-unbuffer
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l debug
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-detect
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-magic
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l strict-magic
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l server-url
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l join-secret
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l max-viewers
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l label
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l share
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l quiet
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l qr
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-qr
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l no-fail-on-bridge
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l unit
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l pattern
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l copy-url
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l strict
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l output
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l config
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l url-file
complete -c fernsicht -f -n '__fish_seen_subcommand_from run' -l webhook
`

const powershellCompletion = `# fernsicht completion for PowerShell. Install:
#   fernsicht completion powershell >> $PROFILE
# Reload your profile (or open a new shell) afterwards.

Register-ArgumentCompleter -Native -CommandName fernsicht -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @(
        @{name='run';        desc='Wrap a command; broadcast progress'}
        @{name='url';        desc='Print URL of running session(s)'}
        @{name='doctor';     desc='Diagnose installation / network'}
        @{name='magic';      desc='Magic-prefix protocol reference'}
        @{name='completion'; desc='Generate shell completion'}
        @{name='update';     desc='Check for / install a newer version'}
        @{name='version';    desc='Print version + build info'}
        @{name='help';       desc='Show help'}
    )

    $tokens = $commandAst.CommandElements
    if ($tokens.Count -le 1) {
        $commands | Where-Object { $_.name -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_.name, $_.name,
                'ParameterValue', $_.desc)
        }
        return
    }

    $cmd = $tokens[1].Value
    switch ($cmd) {
        'completion' {
            'bash','zsh','fish','powershell' | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', "$_ shell")
            }
        }
        'url' {
            '--all','--pid' | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', "url flag")
            }
        }
        'doctor' {
            '--explain','--server-url','--no-color' | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', "doctor flag")
            }
        }
        'update' {
            '--check' | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', "update flag")
            }
        }
        'run' {
            $runFlags = @(
                '--no-pty','--no-unbuffer','--debug',
                '--no-detect','--no-magic','--strict-magic',
                '--server-url','--join-secret','--max-viewers','--label',
                '--share','--quiet','--qr','--no-qr','--no-fail-on-bridge',
                '--unit','--pattern','--copy-url','--strict','--output',
                '--config','--url-file','--webhook'
            )
            $runFlags | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', "run flag")
            }
        }
    }
}
`
